#!/bin/bash

whoami=$(whoami)
if [ "$whoami" != "root" ]; then
    echo "You must be root to execute this script"
    exit 1
fi

if [ ! -d "/etc/nginx" ]; then
	LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/nginx-mainline
	apt install -y nginx-core nginx-common nginx nginx-full
	apt install -y python3-certbot-nginx -y
fi

if [ ! -d "/etc/php/7.4" ]; then
	LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
	
	apt install -y php7.4-{fpm,mysql,cli,common,imap,ldap,xml,curl,mbstring,zip,xmlrpc,soap,gd,intl,mcrypt,opcache,readline,imagick,bcmath}
fi

if [ ! -d "/etc/php/8.0" ]; then
	apt install -y php8.0-{fpm,mysql,cli,common,imap,ldap,xml,curl,mbstring,zip,xmlrpc,soap,gd,intl,mcrypt,opcache,readline,imagick,bcmath}
fi

if [ ! -d "/etc/php/8.1" ]; then
	apt install -y php8.1-{fpm,mysql,cli,common,imap,ldap,xml,curl,mbstring,zip,xmlrpc,soap,gd,intl,mcrypt,opcache,readline,imagick,bcmath}
fi

update-alternatives --set php /usr/bin/php8.0

if [ ! -f "/usr/local/bin/wp" ]; then
    wget -nv https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp
    chmod +x /usr/local/bin/wp
fi